const fs = require('fs');
let content = fs.readFileSync('src/main.js', 'utf8');
content = content.replace(/âš™ï¸ /g, '&#9881;');
content = content.replace(/ðŸ“Š/g, '&#128202;');
content = content.replace(/ðŸ‘—/g, '&#128087;');
content = content.replace(/ðŸ“‚/g, '&#128194;');
content = content.replace(/ðŸ“¦/g, '&#128230;');
content = content.replace(/ðŸ–¼ï¸ /g, '&#128444;');
content = content.replace(/â† /g, '&#8592;');
content = content.replace(/ðŸ”’/g, '&#128274;');
content = content.replace(/â Œ/g, '&#10060;');
content = content.replace(/ðŸ• /g, '&#128341;');
content = content.replace(/âž•/g, '&#10133;');
content = content.replace(/ðŸ“‹/g, '&#128203;');
content = content.replace(/ðŸ’¾/g, '&#128190;');
content = content.replace(/âœ /g, '&#10002;');
content = content.replace(/ðŸ—‘ï¸ /g, '&#128465;');
fs.writeFileSync('src/main.js', content, 'utf8');
console.log('Fixed encoding in main.js');
